language: python
python:
  - 3.6
  - 3.7
install:
  - python setup.py install
  - pip install pytest 
  - pip install codecov
  - git clone https://github.com/orbis-eval/orbis_eval.git;
  - cd orbis_eval;
  - python setup.py install;
  - cd ..;
  - mkdir orbis-eval;
script:
  - pytest
after_success:
  - codecov