language: python
python:
  - 3.6
  - 3.7
install:
  - mkdir ~/orbis-eval;
  
  - git clone https://github.com/orbis-eval/orbis_eval.git;
  - cd orbis_eval;
  - python setup.py install;
  - cd ..;

  - python setup.py install
  - pip install pytest 
  - pip install codecov  
script:
  - pytest
after_success:
  - codecov